apiVersion: v2
name: pgbouncer
description: A Helm chart for deploying pgbouncer on Kubernetes
type: application
version: 1.0.0
appVersion: 1.22.1
kubeVersion: ">= 1.20.0-0"
icon: https://estaid-app.github.io/helm/charts/pgbouncer/pgbouncer.png
keywords:
  - pgbouncer
  - postgresql
  - database
  - connection pool
  - helm
  - kubernetes
maintainers:
  - name: Kaspar Birk
    email: kb@estaid.dk
    url: https://github.com/estaid-app
home: https://github.com/estaid-app/helm
sources:
  - https://github.com/estaid-app/helm/tree/main/charts/pgbouncer
annotations:
  artifacthub.io/license: "MIT"
