apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgbouncer.fullname" . }}-config
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
data:
  pgbouncer.ini: |
    [databases]
{{- range $key, $val := .Values.databases }}
    {{ $key }} ={{ range $k, $v := $val }} {{ $k }}={{ $v }}{{ end }}
{{- end }}
    [pgbouncer]
    listen_addr = *
    listen_port = 5432
    auth_file = /app/data/userlist.txt
    server_reset_query = SELECT pg_advisory_unlock_all()
    server_reset_query_always = 1
{{- range $key, $val := .Values.pgbouncer }}
    {{ $key }} = {{ $val }}
{{- end }}
