apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pgbouncer.fullname" . }}-secret
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
type: Opaque
data:
  adminUser: {{ required "A valid .Values.admin.user entry required!" .Values.admin.user | b64enc | quote }}
  adminPassword: {{ required "A valid .Values.admin.password entry required!" .Values.admin.password | b64enc | quote }}
